#--------------------------------------------------------------------------------------------------------------#
##' Function to read the .sig files and extract spectral data
##'
##' This function reads a .sig file generated by NIRS machine,
##' extract the spectral data and returns it as a data frame.
##'
##'
##' @name read.sig
##' @title read .sig files from SVC
##'
##' @param file_path A character string specifying the path to the .sig file.
##'
##' @return A data data frame with the following columns :
##' \describe{
##' \item{Wavelengths(nm)}{Numeric vector representing the wavelengths in nanometers.}
##' \item{Reference Values}{Numeric vector of reference values.}
##' \item{Target Values}{Numeric vector of target values.}
##' \item{Reflectance(\%)}{Numeric vector of reflectance percentages.}
##' }
##'
##' @details
##' The function first checks if the file exists. If it dosent exist, an error is thrown.
##' The file is then read line by line and the spectral data is extracted from the line after "data=".
##' The extracted data is then converted into a data frame with appropriate names.
##'
##'@examples
##'\dontrun{
##'file_path <- "/path/to/your/file.sig"
##'data <- read.sig(file_path)
##'print(head(data))
##'}
##'
##'@export
##'
##'@author Methun George
##'

read.sig <- function(file_path) {
  if(!file.exists(file_path)) {
    stop("file does not exist: ", file_path)
  }
  #read file contents
  file_content <- readLines(file_path)
  #find start of data
  data_start <- grep("^data=", file_content)
  #extract data lines
  data_lines <- file_content[(data_start + 1):length(file_content)]
  # convert it to data frame
  data <- read.table(text = data_lines, header = FALSE)
  # give names to columns
  colnames(data) <- c("Wavelengths(nm)", "Reference Values", "Target Values", "Reflectance(%)")
  #return the data frame
  return(data)
}

#example data
# file_path <- "/Users/methungeorge/Desktop/IPB/playground/LILY_LEAF_i2145[86].sig"
# data <- read.sig(file_path)
# print(head(data))

